package org.act.com.model;
// Generated Jul 1, 2022 4:22:39 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name="departments",schema="public")
public class Departments  implements java.io.Serializable {


     private long id;
     private Date createdOn;
     private String name;
     private String status;
     private Date updatedOn;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Departments() {
    }

	
    public Departments(long id) {
        this.id = id;
    }
    public Departments(long id, Date createdOn, String name, String status, Date updatedOn, Set<Employee> employees) {
       this.id = id;
       this.createdOn = createdOn;
       this.name = name;
       this.status = status;
       this.updatedOn = updatedOn;
       this.employees = employees;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=29)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="status", length=40)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=29)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="departments")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


