package org.act.com.model;
// Generated Jul 1, 2022 4:22:39 PM by Hibernate Tools 5.2.0.Final


import javax.persistence.*;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name="purchase"
    ,schema="public"
)
public class Purchase  implements java.io.Serializable {


     private long id;
     private PurchaseRequest purchaseRequestId;
     private Resources resourcesId;
     private String authorizedBy;
     private String description;
     private double price;

    public Purchase() {
    }

	
    public Purchase(long id, PurchaseRequest purchaseRequest, Resources resources, double price) {
        this.id = id;
        this.purchaseRequestId = purchaseRequest;
        this.resourcesId = resources;
        this.price = price;
    }
    public Purchase(long id, PurchaseRequest purchaseRequest, Resources resources, String authorizedBy, String description, double price) {
       this.id = id;
       this.purchaseRequestId = purchaseRequest;
       this.resourcesId = resources;
       this.authorizedBy = authorizedBy;
       this.description = description;
       this.price = price;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name= "purchase_request_id", nullable=false)
    public PurchaseRequest getPurchaseRequest() {
        return this.purchaseRequestId;
    }
    
    public void setPurchaseRequest(PurchaseRequest purchaseRequest) {
        this.purchaseRequestId = purchaseRequest;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resource_id", nullable=false)
    public Resources getResources() {
        return this.resourcesId;
    }
    
    public void setResources(Resources resources) {
        this.resourcesId = resources;
    }

    
    @Column(name="authorized_by", length=50)
    public String getAuthorizedBy() {
        return this.authorizedBy;
    }
    
    public void setAuthorizedBy(String authorizedBy) {
        this.authorizedBy = authorizedBy;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", nullable=false, precision=17, scale=17)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


