package org.act.com.model;
// Generated Jul 1, 2022 4:22:39 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * PurchaseRequest generated by hbm2java
 */
@Entity
@Table(name="purchase_request"
    ,schema="public"
)
public class PurchaseRequest  implements java.io.Serializable {


     private long id;
     private Employee employee;
     private String approvedBy;
     private Date createdOn;
     private String productName;
     private Date updatedOn;
     private Set<Purchase> purchases = new HashSet<Purchase>(0);

    public PurchaseRequest() {
    }

	
    public PurchaseRequest(long id, Employee employee, String approvedBy, Date createdOn, String productName, Date updatedOn) {
        this.id = id;
        this.employee = employee;
        this.approvedBy = approvedBy;
        this.createdOn = createdOn;
        this.productName = productName;
        this.updatedOn = updatedOn;
    }
    public PurchaseRequest(long id, Employee employee, String approvedBy, Date createdOn, String productName, Date updatedOn, Set<Purchase> purchases) {
       this.id = id;
       this.employee = employee;
       this.approvedBy = approvedBy;
       this.createdOn = createdOn;
       this.productName = productName;
       this.updatedOn = updatedOn;
       this.purchases = purchases;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="approved_by", nullable=false, length=50)
    public String getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", nullable=false, length=29)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="product_name", nullable=false, length=50)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", nullable=false, length=29)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="purchaseRequest")
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }




}


