package org.act.com.model;
// Generated Jul 1, 2022 4:22:39 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Resources generated by hbm2java
 */
@Entity
@Table(name="resources"
)
public class Resources  implements java.io.Serializable {


     private long id;
     private Date createdOn;
     private String description;
     private String name;
     private String status;
     private Date updatedOn;
     private ResourceType resourceType;






    private Set<Holdings> holdingses = new HashSet<Holdings>(0);
     private Set<Purchase> purchases = new HashSet<Purchase>(0);
     private Set<ResourceRequest> resourceRequests = new HashSet<ResourceRequest>(0);

    public Resources() {
    }

	
    public Resources(long id) {
        this.id = id;
    }
    public Resources(long id, Date createdOn, String description, String name, String status, Date updatedOn, Integer resourceType, Set<Holdings> holdingses, Set<Purchase> purchases, Set<ResourceRequest> resourceRequests) {
       this.id = id;
       this.createdOn = createdOn;
       this.description = description;
       this.name = name;
       this.status = status;
       this.updatedOn = updatedOn;

       this.holdingses = holdingses;
       this.purchases = purchases;
       this.resourceRequests = resourceRequests;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=29)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="status", length=40)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=29)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resource_type")
    public ResourceType getResourceType() {
        return resourceType;
    }
    public void setResourceType(ResourceType resourceType) {
        this.resourceType = resourceType;
    }

    

@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="resources")
    public Set<Holdings> getHoldingses() {
        return this.holdingses;
    }
    
    public void setHoldingses(Set<Holdings> holdingses) {
        this.holdingses = holdingses;
    }
@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="resources")
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }

    @JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="resources")
    public Set<ResourceRequest> getResourceRequests() {
        return this.resourceRequests;
    }
    
    public void setResourceRequests(Set<ResourceRequest> resourceRequests) {
        this.resourceRequests = resourceRequests;
    }




}


