package org.act.com.model;
// Generated Jul 1, 2022 4:22:39 PM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.*;

/**
 * ResourceRequest generated by hbm2java
 */
@Entity
@Table(name="resource_request"
    ,schema="public"
)
public class ResourceRequest  implements java.io.Serializable {


     private long id;
     private Employee employee;
     private Resources resources;
     private String description;
     private Date updatedon;

    public ResourceRequest() {
    }

	
    public ResourceRequest(long id, Employee employee, Resources resources) {
        this.id = id;
        this.employee = employee;
        this.resources = resources;
    }
    public ResourceRequest(long id, Employee employee, Resources resources, String description, Date updatedon) {
       this.id = id;
       this.employee = employee;
       this.resources = resources;
       this.description = description;
       this.updatedon = updatedon;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resource_id", nullable=false)
    public Resources getResources() {
        return this.resources;
    }
    
    public void setResources(Resources resources) {
        this.resources = resources;
    }

    
    @Column(name="description", length=111)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedon", length=29)
    public Date getUpdatedon() {
        return this.updatedon;
    }
    
    public void setUpdatedon(Date updatedon) {
        this.updatedon = updatedon;
    }




}


